development:
  adapter: async

test:
  adapter: test

staging:
  adapter: solid_cable
  connects_to:
    database:
      writing: primary

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: primary