default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: myFr0gg3r!!x
  pool: 5

development:
  <<: *default
  database: stint_dashboard_development


test:
  <<: *default
  database: stint_dashboard_test

staging:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 3) %>

# config/database.yml
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 3) %>
